name: CI

on:
  push:
    branches: [main]

jobs:
  rpm-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Current Repository
        uses: actions/checkout@v2
        with:
          path: ./repo
          ref: gh-pages

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build Repo
        run: docker run --rm
          -v "${PWD}/repo:/repo"
          -v "${PWD}:/pool"
          -v "${HOME}/.gnupg:/root/.gnupg"
          -e GPG_NAME="Marcel's Red Hat Enterprise Linux Repository <repo@m4rc3l.de>"
          marcelcoding/rpm-manager:latest

      - name: Copy README.md, LICENSE, ...
        run: |
          cp README.md repo/README.md
          cp LICENSE repo/LICENSE 
          cp robots.txt repo/robots.txt
          cp -r config repo

      - name: Deploy Repository
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: repo
          clean: true
          clean-exclude: |
            CNAME

          token: ${{ github.token }}
          # https://github.com/crazy-max/ghaction-github-pages/blob/dev/src/git.ts#L3-L8
          commit-message: Deployed Rpm Repository
          git-config-name: GitHub <noreply@github.com>
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
