name: CI

on:
  push:
    branches: [main]

jobs:
  rpm-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Current Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/rpm.m4rc3l.de
          path: ./repo
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build Repo
        run: docker run --rm
          -v "${PWD}/repo:/repo"
          -v "${PWD}:/pool"
          -v "${HOME}/.gnupg:/root/.gnupg"
          -e GPG_NAME="Marcel's Red Hat Enterprise Linux Repository <repo@m4rc3l.de>"
          marcelcoding/rpm-manager:latest

      - name: Copy README.md
        run: |
          cp LICENSE repo/LICENSE 
          cp _redirects repo/_redirects
          cp -r config repo

      - name: Deploy Repository
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: ${{ github.repository_owner }}/rpm.m4rc3l.de
          branch: main
          folder: repo
          clean: true

          token: ${{ secrets.GH_PAT }}
          # https://github.com/crazy-max/ghaction-github-pages/blob/dev/src/git.ts#L3-L8
          commit-message: Deploy ${{ github.repository }}
          git-config-name: GitHub
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
